[package]
name        = "authsmith-notify"
description = "Email and webhook notification plugins for AuthSmith"
version.workspace    = true
edition              = "2021"
license.workspace    = true
repository.workspace = true
homepage.workspace   = true
readme.workspace     = true

[dependencies]
authsmith-core = { workspace = true }
async-trait    = { workspace = true }
thiserror      = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
tracing        = { workspace = true }

# smtp feature
lettre         = { workspace = true, optional = true }

# webhook feature
hooksmith-core = { version = "0.1.5", optional = true }

[dev-dependencies]
tokio      = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
smtp    = ["dep:lettre"]
webhook = ["dep:hooksmith-core"]
